sudo: false

os:
  - linux

language: d

d:
  - ldc
  - dmd

env:
  - ARCH="x86_64"

before_install:
  - sudo apt-get install graphviz

script:
  - dub test --build=unittest-cov
  - ls *.dot | xargs dot -Tpng -O

after_success:
  - bash <(curl -s https://codecov.io/bash)
